import { PROMPT_CATEGORIES, type PromptCategory } from './prompt-categories';

export type BuildRecipeCategory = PromptCategory;

export interface BuildRecipe {
  id: string;
  category: BuildRecipeCategory;
  title: string;
  description: string;
  prompt: string;
  tags: string[];
}

export const BUILD_RECIPE_CATEGORIES: BuildRecipeCategory[] = [...PROMPT_CATEGORIES];

export const BUILD_RECIPES: BuildRecipe[] = [
  {
    id: 'build-implement-feature',
    category: 'Build',
    title: 'Implement a feature safely',
    description: 'Plan, edit, run checks, and summarize the final diff.',
    tags: ['feature', 'checks', 'diff'],
    prompt: [
      'Implement this feature in the current workspace:',
      '',
      'Goal:',
      '- <describe the user-visible behavior>',
      '',
      'Constraints:',
      '- Keep changes scoped to the relevant files.',
      '- Follow existing project patterns.',
      '- Run the available typecheck/lint/test/build checks.',
      '- Summarize changed files, checks run, and any remaining risks.',
    ].join('\n'),
  },
  {
    id: 'build-review-diff',
    category: 'Build',
    title: 'Review current changes',
    description: 'Inspect the current diff and report risks before approval.',
    tags: ['review', 'diff', 'quality'],
    prompt: [
      'Review the current workspace changes before I approve them.',
      '',
      'Focus on:',
      '- Bugs or regressions.',
      '- Missing edge cases.',
      '- Missing or weak tests.',
      '- Whether the diff matches the requested behavior.',
      '',
      'Do not make changes unless you find a clear fix that should be applied immediately.',
    ].join('\n'),
  },
  {
    id: 'research-current-answer',
    category: 'Research',
    title: 'Research and answer',
    description: 'Look up current information, cite sources, and give a concise answer.',
    tags: ['web', 'sources', 'answer'],
    prompt: [
      'Research this question using current sources, then answer clearly:',
      '',
      '<question>',
      '',
      'Requirements:',
      '- Use reliable sources.',
      '- Include links for important claims.',
      '- Separate facts from assumptions.',
      '- Keep the answer concise unless more detail is needed.',
    ].join('\n'),
  },
  {
    id: 'research-compare-options',
    category: 'Research',
    title: 'Compare options',
    description: 'Gather tradeoffs and make a practical recommendation.',
    tags: ['compare', 'decision', 'tradeoffs'],
    prompt: [
      'Compare these options and recommend the best practical choice:',
      '',
      'Options:',
      '- <option 1>',
      '- <option 2>',
      '- <option 3>',
      '',
      'Evaluate:',
      '- Cost and effort.',
      '- Reliability and maintainability.',
      '- Risks or lock-in.',
      '- What I should do first.',
    ].join('\n'),
  },
  {
    id: 'automation-draft',
    category: 'Automation',
    title: 'Draft an automation',
    description: 'Turn a recurring task idea into a concrete automation proposal.',
    tags: ['schedule', 'monitor', 'automation'],
    prompt: [
      'Draft an automation for this recurring task:',
      '',
      '<describe what should happen and when>',
      '',
      'Return:',
      '- Proposed schedule in plain English.',
      '- Exact task prompt the automation should run.',
      '- What output I should expect.',
      '- Any assumptions or warnings before saving.',
    ].join('\n'),
  },
  {
    id: 'automation-monitor',
    category: 'Automation',
    title: 'Monitor and report',
    description: 'Design a monitor that checks something and reports only meaningful changes.',
    tags: ['monitor', 'alerts', 'changes'],
    prompt: [
      'Design a monitoring workflow for this:',
      '',
      '<thing to monitor>',
      '',
      'Include:',
      '- What to check.',
      '- How often to check.',
      '- What counts as a meaningful change.',
      '- What the report should include.',
      '- Cases where it should stay quiet.',
    ].join('\n'),
  },
  {
    id: 'files-organize',
    category: 'Files',
    title: 'Organize files',
    description: 'Inspect a folder and propose safe file organization steps.',
    tags: ['files', 'cleanup', 'workspace'],
    prompt: [
      'Inspect the current workspace files and propose a safe organization plan.',
      '',
      'Rules:',
      '- Do not delete files without explicit confirmation.',
      '- Preserve user-created content.',
      '- Identify duplicates, generated files, and stale artifacts separately.',
      '- Provide a concrete step-by-step cleanup plan.',
    ].join('\n'),
  },
  {
    id: 'files-summarize-project',
    category: 'Files',
    title: 'Explain this project',
    description: 'Summarize the app structure, commands, and important files.',
    tags: ['summary', 'onboarding', 'workspace'],
    prompt: [
      'Explain this project from the current workspace.',
      '',
      'Include:',
      '- What the app does.',
      '- The main folders and entry points.',
      '- How to run it locally.',
      '- How to test or build it.',
      '- Important risks or setup requirements.',
    ].join('\n'),
  },
  {
    id: 'connectors-add-integration',
    category: 'Connectors',
    title: 'Add an integration',
    description: 'Plan and implement a connector or external service integration.',
    tags: ['connector', 'api', 'integration'],
    prompt: [
      'Plan and implement this integration:',
      '',
      '<service or connector>',
      '',
      'Requirements:',
      '- Identify required credentials and where they should be stored.',
      '- Follow existing connector/plugin patterns.',
      '- Add user-visible error handling.',
      '- Add focused tests or a manual verification checklist.',
    ].join('\n'),
  },
  {
    id: 'connectors-debug',
    category: 'Connectors',
    title: 'Debug connector failure',
    description: 'Diagnose why a connector, API, or plugin call is failing.',
    tags: ['debug', 'connector', 'api'],
    prompt: [
      'Debug this connector/API/plugin failure:',
      '',
      '<paste error or describe behavior>',
      '',
      'Investigate:',
      '- Configuration and credentials.',
      '- Request/response shape.',
      '- Permission or network failures.',
      '- Recent code paths that could affect it.',
      '',
      'Return the root cause and the smallest safe fix.',
    ].join('\n'),
  },
  {
    id: 'troubleshoot-runtime',
    category: 'Troubleshooting',
    title: 'Fix runtime failure',
    description: 'Use logs and project state to repair a broken dev/runtime preview.',
    tags: ['runtime', 'logs', 'repair'],
    prompt: [
      'Diagnose and fix the current runtime failure.',
      '',
      'Use:',
      '- Runtime logs.',
      '- Current workspace files.',
      '- Package scripts and framework config.',
      '',
      'Steps:',
      '- Identify the first real error.',
      '- Apply the smallest fix.',
      '- Restart or rerun checks if needed.',
      '- Summarize the fix and remaining risk.',
    ].join('\n'),
  },
  {
    id: 'troubleshoot-tests',
    category: 'Troubleshooting',
    title: 'Fix failing checks',
    description: 'Run or inspect checks and fix failures without broad refactors.',
    tags: ['tests', 'typecheck', 'lint'],
    prompt: [
      'Fix the failing checks in this workspace.',
      '',
      'Process:',
      '- Run or inspect the relevant typecheck, lint, test, and build checks.',
      '- Identify the smallest cause of failure.',
      '- Fix only the relevant files.',
      '- Rerun the failed checks.',
      '- Summarize what changed and what still was not verified.',
    ].join('\n'),
  },
];
